version: '3.4'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432
  app:
    build: .
    volumes:
      - ./rails:/rails
    environment:
      - RAILS_ENV=development
    depends_on:
      - db