version: '3.4'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_app
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - RAILS_ENV=development

  database:
    image: postgres:12.3-alpine
    restart: always
    container_name: postgres_database
    environment: 
      - POSTGRES_PASSWORD=duur#hashnaRo243
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"

volumes:
  gem_cache:
  db_data:
  node_modules: